### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by iamdriz** [huseyinbabal/token-based-auth-backend#1]
Hi, I'm looking at borrowing some ideas from this for a project that will use AngularJS, NodeJS and Express. And requires the ability to track users being logged in (hence looking at this project).

However I haven't seen anywhere in the code where you handle the expiration of the token and request that the user re-login to generate a new token. Have I missed this?

**Comment by huseyinbabal** [comment]
Hi,

You can do it by your self by setting expire date. However, you need to check token expiration on each use. Please refer [here](http://stackoverflow.com/questions/23626823/json-web-token-does-not-expire) for more details
