### ISSUE TITLE
uncaghtException 'iat' of undefined

### ISSUE THREAD

**Issue by image72** [huseyinbabal/token-based-auth-backend#2]
hi,I pull project, step to sign up, get this error 

``` javascript

OPTIONS /signin 200 14.514 ms - 4
/Users/someuser/projects/token-based-auth-backend/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot set property 'iat' of undefined
    at Object.module.exports.sign (/Users/someuser/projects/token-based-auth-backend/node_modules/jsonwebtoken/index.js:12:15)
```

is mongodb schema define error ?

**Comment by jdhrivas** [comment]
I'm having the same issue. Did you figure it out?

**Comment by dioptre** [comment]
i saw this too....

**Comment by hurquiza** [comment]
update package.json, versions are too old. This causes the following error:
{ [MongoError: driver is incompatible with this server version] name: 'MongoError' }

which is unhandled.

**Comment by hurquiza** [comment]
Confirmed: updated package.json, ran npm install and now backend is working like a charm :)

**Comment by YDSUDARSHANA** [comment]
update package.json with most as >= and hit NPM update. Also iat error dissapered after i addded iat:Date as a member in the schema

**Comment by Ameydesai07** [comment]
The issue is still persist, though i have updated the package dependencies with the latest one. Any help would be appreciated.
